__Assignment 1__

In [17]:
import numpy as np

In [18]:
b = np.array([-3,-8,7])

In [19]:
A = np.array([[-10,3,11],
            [3,-5,-4],
            [11,-4,-7]])
print(A)

[[-10   3  11]
 [  3  -5  -4]
 [ 11  -4  -7]]


__*Check Symmetry*__

needs to satisfy the following : A=A^T

In my opinion it is symetric

In [20]:
def check_equality(A,AT):
    return np.array_equal(A,AT)

In [21]:
check = check_equality(A,A.T)
print(f'Is matrix A symmetric? {check}')

Is matrix A symmetric? True


__*Solution to Ax=b*__


*define a function that solves the system *

In [22]:
def solve_linear_system(A,b):
    x = np.linalg.solve(A,b)
    return x

In [23]:
# call the function
x = solve_linear_system(A,b)
print(f"the solution of Ax=b is : {x} ")

the solution of Ax=b is : [2. 2. 1.] 


__*Calculate r to check solution*__

In [24]:
r = np.dot(A,x)
print(f"r is effectively : {r}")

r is effectively : [-3. -8.  7.]


__*Print the difference of r and b *__

The difference should be 0 because the solution to Ax=b returns the valuues of x for which Ax is equal to b so if we multiply A with x we retrieve r which effectively means : 

Ax = b = r = Ax ---> r-b = 0

now when we deals with norms we try to seek the distance between vectors and in this case given that they are the same the distance is 0.

We have to take into account that floating-point numbers normally introduce rounding errors which can result in numbers not exactly equal to 0 but close to it.

In [25]:
diff = np.linalg.norm(r-b)
print(f'the difference is {diff}')

the difference is 3.580361673049448e-15


__*Print det of A*__

In [26]:
det = np.linalg.det(A)
print(f'the determinant of A is : {det}')

the determinant of A is : 214.0000000000001


In [27]:
A2 = np.array([[-1,3000,1],
                [2000, -1.5, -2.5],
                [-1999, -2998.5, 1.5]])
print(A2)

[[-1.0000e+00  3.0000e+03  1.0000e+00]
 [ 2.0000e+03 -1.5000e+00 -2.5000e+00]
 [-1.9990e+03 -2.9985e+03  1.5000e+00]]


__*Check symmetry*__

In my opinion it is not symmetric

In [28]:
checkA2 = check_equality(A2,A2.T)
print(f'Is matrix A symmetric? {checkA2}')

Is matrix A symmetric? False


__*Solve the system*__

In [29]:
x2 = solve_linear_system(A2,b)
print(f"the solution of Ax=b is : {x2} ")

the solution of Ax=b is : [ 2.25135002e+13 -5.99729500e+12  1.80143985e+16] 


__*Calculate r2 to check the solution*__

In [30]:
r2 = np.dot(A2,x2)
print(f"r is effectively : {r2}")

r is effectively : [-4. -8.  8.]


__*Print the difference of r2 and b*__

The difference should be 0 because the solution to A2x2=b returns the valuues of x for which A2x2 is equal to b so if we multiply A2 with x we retrieve r2 which effectively means : 

A2x2 = b = r2 = A2x2 ---> r2-b = 0

now when we deals with norms we try to seek the distance between vectors and in this case given that they are the same the distance is 0.

The norm results in a very large number compared to the first matrix A due to numpy using numerical methods and not analytical ones. Given the fact that the matrix is close o be non-invertible given the determinant is very close to 0 it is very close to being singular. Due to this small floating-floating errors gets larger. This enlarges the result. The determinant of the first  is very large so the result of the norm is more precise

In [31]:
diffA2 = np.linalg.norm(r2-b)
print(f'the difference is {diffA2}')

the difference is 1.4142135623730951


__*Print det of A2*__

In [32]:
detA2 = np.linalg.det(A2)
print(f'the determinant of A is : {detA2}')

the determinant of A is : 1.3322672964832825e-09


determinant is very very close to 0 this means that is close to be non-invertible. Compared to the A, it is not symmetric so its transposed is not equal to itself.